services:
  grafana:
    build: .
    ports:
      - "3000:3000"
    #network_mode: host  # Use host networking
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini

volumes:
  grafana-storage:
